import "~/styles/globals.css";
import { type Metadata } from "next";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


import {SessionProvider} from "next-auth/react";

export default function AuthLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <div className="min-h-screen flex">
        <div className="w-full  flex items-center justify-center">
          <SessionProvider>
            <div className="w-full">
              {children}
            </div>
          </SessionProvider>
        </div>
      </div>
    )
  }
