import "~/styles/globals.css";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import { Manrope } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap"
});


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap"
});


import { ThemeProvider } from "~/components/theme-provider"
// import Navbar from "./_components/navbar";
import { SessionProvider } from "next-auth/react";

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>
        <head />
        <body className="font-sans">
          <SessionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TRPCReactProvider>
                <div className="">{children}</div></TRPCReactProvider>
            </ThemeProvider>
          </SessionProvider>
        </body>
      </html>
    </>
  )
}
