import "~/styles/globals.css";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "sonner"
// import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


import { ThemeProvider } from "~/components/theme-provider"
// import Navbar from "./_components/navbar";
import { SessionProvider } from "next-auth/react";

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <html lang="en"  suppressHydrationWarning>
        <head />
        <body className="font-sans">
          <SessionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TRPCReactProvider>
                <div className="">{children}</div></TRPCReactProvider>
                <Toaster />
            </ThemeProvider>
          </SessionProvider>
        </body>
      </html>
    </>
  )
}



